apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: container-kill-example
  namespace: chaos-testing
spec:
  action: container-kill
  mode: one
  containerName: 'kafka-consumer'
  selector:
    labelSelectors:
      'app': 'p2sopes-kafka'
  scheduler:
    cron: '@every 60s'
