apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - project
    labelSelectors:
      'app': 'p2sopes-pubsub'
  scheduler:
    cron: '@every 30s'
