apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: one
  value: ''
  duration: '60s'
  selector:
    labelSelectors:
      'app': 'p2sopes-pubsub'
  scheduler:
    cron: '@every 2m'
