apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2sopes-pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2sopes-pubsub
  template:
    metadata:
      labels:
        app: p2sopes-pubsub
    spec:
      containers:
      - name: pubsub-client
        image: randycan/pubsub-client
        ports:
        - containerPort: 3001
      - name: pubsub-server
        image: randycan/pubsub-server
