version: "3.3"
services:

  mongodb:
     container_name: "mongodb"
     image: "mongo:latest"
     ports:
        - "27017:27017"
     networks: 
       - "networkapi"
  servenode:
  
      container_name: "test_serve"
      build: .
      ports:
        - "3000:3000"
      volumes: 
          - /proc/:/elements/procs/
      networks: 
        - "networkapi"
  
networks:
  networkapi:
    driver: "bridge"
